version: "3.8"

services:
  jenkins:
    build:
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    ports:
      - 8082:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
