version: "3.8"

services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - 4444:4444
    networks:
      - selenoid
    environment:
      - DOCKER_API_VERSION=1.50
    volumes:
      - ./selenoid:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    networks:
      - selenoid
    ports:
      - 9090:8080
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  selenoid:
    name: selenoid